apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: ghcr.io/jainnpiy/demo:c8b554dd2aae5d88bfb80e4860f898077007e31b
          ports:
            - containerPort: 80
          imagePullPolicy: Always