apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: ghcr.io/jainnpiy/demo:d4b099e6bfd873f3d9e08f9e384e77b07872a00f
          ports:
            - containerPort: 80
          imagePullPolicy: Always