apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: ghcr.io/jainnpiy/demo:86351cfbd8e7ccf6a850cfaac5206af30368a28b
          ports:
            - containerPort: 80
          imagePullPolicy: Always